# Generated by Django 4.2 on 2025-12-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BSApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=50)),
                ("content", models.CharField(max_length=500)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
