# Generated by Django 4.2 on 2025-12-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BSApp", "0002_post_delete_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
