# Generated by Django 4.2 on 2025-12-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BSApp", "0003_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=30),
        ),
    ]
